# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "addressable"
gem "nokogiri"
gem "curb"
gem "ruby-filemagic"
gem "mime-types"

